spring.application.name=bank-legacy

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.batch.jdbc.initialize-schema=always
spring.batch.jdbc.isolation-level-for-create=READ_COMMITTED
spring.sql.init.mode=always
spring.sql.init.continue-on-error=true
# Escalamiento Semana 3
batch.scaling.grid-size=4
batch.scaling.threads=4
batch.scaling.chunk-size=25
batch.input.total-items=1000
batch.fault-tolerance.max-skips=1000
batch.fault-tolerance.max-retries=2
batch.fault-tolerance.retry-delay-ms=200
batch.fault-tolerance.simulate-transient-failure=false
