CREATE TABLE DAILY_TRANSACTION (
    ID      NUMBER          PRIMARY KEY,
    FECHA   DATE            NOT NULL,
    MONTO   NUMBER(18,2)    NOT NULL,
    TIPO    VARCHAR2(20)    NOT NULL
);
CREATE TABLE MONTHLY_INTEREST (
    CUENTA_ID      NUMBER          PRIMARY KEY,
    NOMBRE         VARCHAR2(100)   NOT NULL,
    SALDO_INICIAL  NUMBER(18,2)    NOT NULL,
    EDAD           NUMBER          NOT NULL,
    TIPO           VARCHAR2(20)    NOT NULL,
    INTERES        NUMBER(18,2)    NOT NULL,
    SALDO_FINAL    NUMBER(18,2)    NOT NULL
);

CREATE TABLE ANNUAL_ACCOUNT_ENTRY (
    MOVIMIENTO_ID  NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CUENTA_ID      NUMBER          NOT NULL,
    FECHA          DATE            NOT NULL,
    TRANSACCION    VARCHAR2(30)    NOT NULL,
    MONTO          NUMBER(18,2)    NOT NULL,
    DESCRIPCION    VARCHAR2(255)   NOT NULL
);
