server.port=8441

server.ssl.enabled=true
server.ssl.key-store=${BFF_TLS_KEYSTORE_PATH}
server.ssl.key-store-password=${BFF_TLS_KEYSTORE_PASSWORD}
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=bank-bff-local