server.port=8093
bank.service.description=Movement microservice configuration from Config Server

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
# Circuit Breaker Oracle
resilience4j.circuitbreaker.instances.movementDatabase.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.movementDatabase.sliding-window-size=4
resilience4j.circuitbreaker.instances.movementDatabase.minimum-number-of-calls=2
resilience4j.circuitbreaker.instances.movementDatabase.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.movementDatabase.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.movementDatabase.permitted-number-of-calls-in-half-open-state=1
resilience4j.circuitbreaker.instances.movementDatabase.automatic-transition-from-open-to-half-open-enabled=true
spring.cloud.circuitbreaker.resilience4j.disable-time-limiter-map.movementDatabase=true