server.port=8092
bank.service.description=Transaction microservice configuration from Config Server

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
# Circuit Breaker Oracle
resilience4j.circuitbreaker.instances.transactionDatabase.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.transactionDatabase.sliding-window-size=4
resilience4j.circuitbreaker.instances.transactionDatabase.minimum-number-of-calls=2
resilience4j.circuitbreaker.instances.transactionDatabase.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.transactionDatabase.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.transactionDatabase.permitted-number-of-calls-in-half-open-state=1
resilience4j.circuitbreaker.instances.transactionDatabase.automatic-transition-from-open-to-half-open-enabled=true
