spring.application.name=authorization-server
server.port=9000

bank.oauth2.client-id=${OAUTH2_CLIENT_ID}
bank.oauth2.client-secret=${OAUTH2_CLIENT_SECRET}
bank.oauth2.issuer=${OAUTH2_ISSUER_URI:http://localhost:9000}